apiVersion: v1
kind: Deployment
metadata:
  name: nginx-lab
spec:
  replicas: 2
  selector:
    matchLables:
      app: nginx-lab
    template:
      metadata:
        labels:
          app: nginx-lab
      specs:
        containers:
          - name: nginx
            image: nginx
            volumeMounts:
              - name: html
                mountPath: /usr/share//nginx/html
        volumes:
          - name: html
            configMap:
              name: index-html

  